version: "3.7"

# Database + Webserver (under http, for testing setup on localhost:80)
#
# docker-compose -f docker-compose.dev.yml up -d
#

services:
  database:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
  api:
    depends_on:
      - database
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DEFAULT_DATABASE_HOSTNAME=postgres
      - DEFAULT_DATABASE_PORT=5432
    ports:
      - 80:8000

volumes:
  database_data:
