"""set_foreign_key_to_heroes

Revision ID: 20a4cd06f4f9
Revises: e8fdc40aa2dd
Create Date: 2023-06-04 19:56:06.065360

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "20a4cd06f4f9"
down_revision = "e8fdc40aa2dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hrs_heroes",
        sa.Column("user_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_foreign_key(None, "hrs_heroes", "hrs_users", ["user_uuid"], ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hrs_heroes", type_="foreignkey")
    op.drop_column("hrs_heroes", "user_uuid")
    # ### end Alembic commands ###
